### ISSUE TITLE
Field updates

### ISSUE THREAD

**Issue by shanewilson** [NCI-GDC/gdc-models#2]
`consequence` needs `consequence_id` field
`occurrence` needs `occurrence_id` field
`observation` needs `observation_id` field
consequence has a `gene_symbol` next to `gene` which should be removed

gene_centric
`transcript.id` => `transcript.transcript_id`

**Comment by junjun-zhang** [comment]
All these are done, will update mappings soon to reflect the changes.

**Comment by junjun-zhang** [comment]
This is done in #7
