### ISSUE TITLE
remove unneeded biospec_id fields on gdc_from_graph case

### ISSUE THREAD

**Issue by shanewilson** [NCI-GDC/gdc-models#24]
This was done for the new indexes but not the gdc_from_graph indexes:

https://github.com/NCI-GDC/gdc-models/blob/master/es-models/gdc_from_graph/case.mapping.yaml#L2

**Comment by lindaxiang** [comment]
Hey @shanewilson,  as we mentioned in https://jira.opensciencedatacloud.org/browse/DAT-680:
"remove 'case.*_ids' fields for viz indexes. These were added for keyword search, no need now. Note, we don't remove them from 'gdc_from_graph.case' yet"
So we only removed *_ids from case_centric index not for gdc_from_graph. As the data for gdc_from_graph was dumped from es-build, we do not have control of that.

**Comment by junjun-zhang** [comment]
This needs to be done by ESbuild, until then we don't change the mapping. Will create new ticket for it when it's ready to do so.
