### ISSUE TITLE
'annotation' should be under 'ssm', not deeper

### ISSUE THREAD

**Issue by DrSpez** [NCI-GDC/gdc-models#25]
Since `annotation` field is a property of a `ssm`, there is no need to duplicate `annotation` data beneath `ssm` level.
Now `annotation` is way too deep: (for ex. in gene_centric: `gene.case.ssm.consequence.transcript.annotation`), and it should be moved to just `gene.case.ssm.annotation`. (same for all other indices)

**Comment by junjun-zhang** [comment]
> the ones that are safe to be lifted to ssm_id level `dbSNP_RS, dbSNP_Val_Status, cosmic_id, Existing_Variation`

We did move `cosmic_id` up to `ssm` level, the other four were kept unchanged to minimize the mapping changes, will be moved later.

The reason other fields are not safe to move is that they are `transcript` dependent, and maintaining `annotation` under transcript structure is preparing for future growth as well. Although only one of the transcripts is fully annotated, in the future all other transcripts may get the same level of annotation.

**Comment by junjun-zhang** [comment]
Already discussed, won't fix
