### ISSUE TITLE
remove unneeded biospec_id fields on case

### ISSUE THREAD

**Issue by shanewilson** [NCI-GDC/gdc-models#3]
we have bunch biospec id fields (sampe_ids, aliquot _ids etc..) that we need for quicksearch but don't anymore.
We should remove them all.

**Comment by junjun-zhang** [comment]
I am ok with this. How do you think, @dankolbman ?

**Comment by dankolbman** [comment]
yeah 👍, that sounds good to me.

**Comment by junjun-zhang** [comment]
This should be easy to do in `case_centric` index, but `gdc_from_grahp.case` is a different story. Maybe not to touch them for the first viz release.

**Comment by dankolbman** [comment]
`gdc_from_graph.case` is already different from `case_centric`, so I don't think it should be a major change.

**Comment by junjun-zhang** [comment]
this is done in #7
