### ISSUE TITLE
Update `max_result_window` value to 100mil for all indexes

### ISSUE THREAD

**Issue by Jephuff** [NCI-GDC/gdc-models#32]

**Comment by junjun-zhang** [comment]
We can do that for each index setting. But here is a useful tip: https://discuss.elastic.co/t/making-index-max-result-window-setting-persistent/63273, to make it a persisted global setting for any new indexes.

**Comment by junjun-zhang** [comment]
This is addressed here: https://github.com/NCI-GDC/gdc-models/pull/34
