### ISSUE TITLE
Make YAML file sort by keys to allow easy diff comparison

### ISSUE THREAD

**Issue by junjun-zhang** [NCI-GDC/gdc-models#42]
The initial idea to preserve YAML original key order was to allow exact round-trip after formatting. As such, Python library `ruamel.yaml` was chosen to ensure that, and it also supports preserving `comments` (although we found out in practice we rare use or need to use comments).

As we will likely need to move forward to generate ES mappings using scripts (at least certain part of the mappings may be desirable to be generated programmatically). In order to clearly view changes made in updated (or about to be updated) mappings using `git diff`, it would be more desirable, YAML keys are sorted in a consistent way.

If we decide to go forward with this, we just need to update the 'pre-commit' git hook script to always format YAML before perform git commit.

**Comment by junjun-zhang** [comment]
@DrSpez @christiandompierre: what do you think?

**Comment by christiandompierre** [comment]
sounds good to me

**Comment by jbarno** [comment]
Ran into this when trying to script adding fields. `jbarno/update_fields` implementation would get a lot easier if the yaml was always sorted.

**Comment by junjun-zhang** [comment]
addressed in #48
