### ISSUE TITLE
Remove index settings

### ISSUE THREAD

**Issue by dankolbman** [NCI-GDC/gdc-models#5]
Is this an appropriate repo to be storing index settings in, like primary and shard counts? It seems that should be up to whatever is utilizing the mappings as it may vary by application.

**Comment by junjun-zhang** [comment]
Good point. As we progress on, there will be more this type of questions coming up. We still need ES settings here for defining custom analyzer. Shards setting is indeed not needed, just a copy & paste artifact, will remove.

**Comment by dankolbman** [comment]
I'm wondering if maybe some utility functions may be desirable? It may be easier to have a `construct_mapping(*settings)` sort of function seeing as most all but a handful of variables for settings are defined in this repo.

**Comment by junjun-zhang** [comment]
Yea, in principle, I'd like to keep the models completely static for easy maintenance and change tracking. Maybe the clients consumes the data models here can have some kind of ability (with it's own code) to alter certain aspects of the data models. One example is that the ES mapping 'dynamic' setting, for production it's good to set to 'strict', but for development, you may want to set to 'false'.

Let's see how it goes, if it becomes obvious we need to do a lot of dynamic things, we should then come up with some sensible solutions.

**Comment by junjun-zhang** [comment]
Closing this for now, will create new issue when needs raise
