### ISSUE TITLE
case.project.primary_site -> case.project.primary_sites[]

### ISSUE THREAD

**Issue by shanewilson** [NCI-GDC/gdc-models#6]
I'm not sure if this ticket is needed - it might just be a collab thing but right now project.primary_site/disease_type and case.project.primary_site/disease_type is a string but should be an array
Also would be good to call them primary_sites and disease_types.

**Comment by junjun-zhang** [comment]
Pending verification from UC side

**Comment by junjun-zhang** [comment]
Verified from @dankolbman, there has been no structural change in the `gdc_from_graph` index.

If it's only concerning change the value from `string` to an array of `string`, there is no need to change anything in this model repository. The current ES mapping will just work.

**Comment by shanewilson** [comment]
the data should be entered as an array not a string.
